# PyTorch Fundamental Exercises

[Tutorial on pytorch fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/)

References:
  * Pytorch documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * Pytorch documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 1. Create a random tensor with shape `(7, 7)`.

The output should look like:

```
tensor([[0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967],
        [0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730],
        [0.6186, 0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743],
        [0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630, 0.8405],
        [0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742]])
```

In [4]:
import torch
rand_7x7 = torch.rand([7, 7])
rand_7x7


tensor([[0.0411, 0.2018, 0.1174, 0.8998, 0.0574, 0.0607, 0.1121],
        [0.8275, 0.4306, 0.8811, 0.5606, 0.0960, 0.0394, 0.4019],
        [0.0476, 0.5632, 0.3141, 0.8115, 0.3747, 0.6695, 0.4590],
        [0.3151, 0.6184, 0.4442, 0.5056, 0.5002, 0.8509, 0.1954],
        [0.8189, 0.8245, 0.9081, 0.8927, 0.9866, 0.8036, 0.8202],
        [0.5640, 0.7067, 0.6187, 0.4358, 0.5730, 0.6417, 0.3931],
        [0.4447, 0.9535, 0.6204, 0.8149, 0.7349, 0.0137, 0.5542]])

### 2. Perform a matrix multiplication on the tensor from 1 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

The output should look like:

```
(tensor([[1.1939],
         [1.1061],
         [0.9868],
         [1.8999],
         [0.7716],
         [1.3174],
         [1.6353]]),
 torch.Size([7, 1]))
```

In [7]:
rand_1x7 = torch.rand([1, 7])
rand_7x7 @ rand_1x7.T

tensor([[0.7672],
        [1.4572],
        [1.3303],
        [1.3185],
        [2.7398],
        [1.6386],
        [2.0003]])

### 3. Set the random seed to `0` and do 1 & 2 over again.

The output should look like:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))
```

In [9]:
torch.manual_seed(0)
rand_7x7 = torch.rand([7, 7])
rand_1x7 = torch.rand([1, 7])
rand_7x7 @ rand_1x7.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 4. Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set a manual seed of 1234 when creating the tensors.

The output should look like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
torch.manual_seed(1234)
device = "cuda"

t1 = torch.rand([2, 3])
t2 = torch.rand([2, 3])

t1 = t1.to(device)
t2 = t2.to(device)

print(f"t1={t1}\nt2={t2}")




t1=tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
t2=tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 5. Perform an element-wise addition on the tensors you created in 4. What happens if you move one of the tensors back to CPU and try to do the addition then?

The output should look like:
```
(tensor([[0.0808, 0.8700, 0.9337],
         [0.6981, 0.8420, 1.2637]], device='cuda:0'),
 torch.Size([2, 3]))
```

In [23]:
print(f"t1+t2 = {t1+t2}")

device = "cpu"

t1 = t1.to(device)
t2 = t2.to(device)

print(f"t1+t2 = {t1+t2}")
t3 = t1+t2



t1+t2 = tensor([[0.0808, 0.8700, 0.9337],
        [0.6981, 0.8420, 1.2637]])
t1+t2 = tensor([[0.0808, 0.8700, 0.9337],
        [0.6981, 0.8420, 1.2637]])


### 6. Find the maximum and minimum values of the output of 5.

The output should look like:

```
Max: 0.5617256760597229
Min: 0.3647301495075226
```

In [26]:
print(f"max = {t3.max()}")
print(f"min = {t3.min()}")

max = 1.2637078762054443
min = 0.0807766318321228


### 7. Find the maximum and minimum index values of the output of 6.

The output should look like:

```
Max index: 3
Min index: 0
```

In [27]:
print(f"argmax = {t3.argmax()}")
print(f"argmin = {t3.argmin()}")

argmax = 5
argmin = 0



### 8. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
torch.manual_seed(7)
t1 = torch.rand([1, 1, 1, 10])
print(f"original = {t1}\nshape = {t1.shape}")
t1 = t1.squeeze()
print(f"squeezed = {t1}\nshape = {t1.shape}")


original = tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
shape = torch.Size([1, 1, 1, 10])
squeezed = tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
shape = torch.Size([10])


### 9. Make a random tensor with shape `(10, 3, 4)`. Add a fourth dimension to the second axis of this tensor so that the shape will be `(10, 1, 3, 4)`.

The output should look like:

```
(torch.Size([10, 3, 4]), torch.Size([10, 1, 3, 4]))
```

In [31]:
t1 = torch.rand([10, 3, 4])
print(f"original = {t1}\nshape = {t1.shape}")
t1 = t1.unsqueeze(1)
print(f"unsqueezed = {t1}\n shape = {t1.shape}")

original = tensor([[[0.6206, 0.4684, 0.3571, 0.9390],
         [0.0195, 0.7833, 0.6358, 0.8134],
         [0.2102, 0.3361, 0.2899, 0.9852]],

        [[0.4354, 0.0232, 0.7507, 0.5964],
         [0.5684, 0.1666, 0.0316, 0.9531],
         [0.1234, 0.4050, 0.4084, 0.7855]],

        [[0.0785, 0.2138, 0.2321, 0.2479],
         [0.8059, 0.8061, 0.7268, 0.9081],
         [0.1675, 0.4980, 0.0954, 0.4990]],

        [[0.0727, 0.0184, 0.8149, 0.2787],
         [0.4602, 0.3526, 0.1034, 0.4501],
         [0.5739, 0.8995, 0.2873, 0.9764]],

        [[0.2685, 0.8200, 0.9367, 0.5517],
         [0.3283, 0.8699, 0.3542, 0.2859],
         [0.3257, 0.0922, 0.4500, 0.0932]],

        [[0.8274, 0.0184, 0.1285, 0.5991],
         [0.8093, 0.9782, 0.0948, 0.9107],
         [0.8503, 0.1720, 0.7085, 0.3594]],

        [[0.6439, 0.0574, 0.2129, 0.1830],
         [0.4025, 0.4818, 0.4892, 0.2046],
         [0.7470, 0.7540, 0.0614, 0.0365]],

        [[0.3926, 0.6391, 0.1192, 0.4540],
         [0.5284, 0.1179, 0.9

### 10. Make a python list containing 5 tensors with shape `(3, 4)` where all values are zero (use a loop). Stack all tensors in the list together to one big tensor with shape `(5, 3, 4)`.

The output should look like:

```
(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.Size([5, 3, 4]))
```

In [36]:
l = []
for i in range(5):
    l.append(torch.zeros([3, 4]))

tensor = torch.stack(l)
print(f"tensor = {tensor}\nshape = {tensor.shape}")

tensor = tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
shape = torch.Size([5, 3, 4])


### 11. Make a tensor with `torch.arange(0, 10)`. Print out the first 3 numbers, the last 4 numbers, and all numbers except the first and last one.

The output should look like:

```
tensor([0, 1, 2])
tensor([6, 7, 8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
```

In [44]:
t1 = torch.arange(0, 10)
print(f"t1[:3] = {t1[:3]}\t t1[6:] = {t1[6:]}\t t1[1:10] = {t1[1:9]}")

t1[:3] = tensor([0, 1, 2])	 t1[6:] = tensor([6, 7, 8, 9])	 t1[1:10] = tensor([1, 2, 3, 4, 5, 6, 7, 8])
